languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "HQBW"
logo = "img/blowfish_logo_transparent.png"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Mike"
  image = "static/apple-touch-icon.png"
  headline = "A powerful, theme for Hugo built with Tailwind CSS."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  links = [
    { twitter = "https://twitter.com/HQBW" },
  #  { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/mike776" },
  ]
